// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions: plateforme non supportée. '
          'Urbink cible iOS et Android uniquement.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJChis4kpKK-y0-QEgUVOp0ixYFmaUvCE',
    appId: '1:748881819569:android:5d53d81bd1bc90a41e2f90',
    messagingSenderId: '748881819569',
    projectId: 'urbink-dev',
    storageBucket: 'urbink-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMMqBkfaQNACd47sxsdjJHsQvms4jXAFg',
    appId: '1:748881819569:ios:cdb118145112e0131e2f90',
    messagingSenderId: '748881819569',
    projectId: 'urbink-dev',
    storageBucket: 'urbink-dev.firebasestorage.app',
    iosBundleId: 'com.example.urbink',
  );
}
